<?php

namespace GestionBundle\Repository\rrhh;

/**
 * PropietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropietarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPropietarios()
	{
		$data =  $this->createQueryBuilder('p')
						->orderBy('p.razonSocial')
					    ->getQuery()
					    ->getResult();
		return $data;
	}
}
