<?php

namespace GestionBundle\Repository\rrhh;

/**
 * TipoVencimientoPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoVencimientoPersonalRepository extends \Doctrine\ORM\EntityRepository
{
}
