<?php

namespace GestionBundle\Repository\segVial;

/**
 * UnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUnidades()
	{
		$data =  $this->createQueryBuilder('u')
						->join('u.propietario', 'p')
						->orderBy('p.razonSocial')
					    ->addOrderBy('u.interno')
					    ->getQuery()
					    ->getResult();
		return $data;
	}

	public function getListaUnidades(\AppBundle\Entity\Usuario $user, \AppBundle\Entity\Estructura $estructura = null)
	{
		$strs = new \Doctrine\Common\Collections\ArrayCollection();
		if ($estructura)
		{
			if (!$user->contieneEstructura($estructura))
			{
				return [];
			}
			else
			{
				$strs[] = $estructura;
			}
		}
		else
		{
	        return $this->getEntityManager()
	                ->createQuery('SELECT u
	                               FROM GestionBundle\Entity\segVial\Unidad u
	                               INNER JOIN AppBundle\Entity\Usuario us WITH u.estructuraHabitual MEMBER OF us.estructuras
	                               WHERE us = :usuario
	                               ORDER BY u.interno')
	                ->setParameter('usuario', $user)
	                ->getResult();
		}




	}
}
