<?php

namespace AppBundle\Repository;

/**
 * CampoInformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoInformeRepository extends \Doctrine\ORM\EntityRepository
{
}
