<?php

namespace AppBundle\Repository;

/**
 * DefinicionInformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefinicionInformeRepository extends \Doctrine\ORM\EntityRepository
{
}
