<?php

namespace AppBundle\Repository;

/**
 * EstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
