<?php

namespace AppBundle\Repository;

/**
 * UsuarioEstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioEstructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
