<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{

	public function getUserAdministrador($username)
	{
		$query = $this->getEntityManager()
		            ->createQuery(
		                			'SELECT u 
		                			 FROM AppBundle:Usuario u 
		                			 WHERE u.activo = :activo AND u.username = :username AND u.roles LIKE :role'
		            )->setParameter('role', '%"ROLE_CREATOR"%')
		             ->setParameter('activo', true)
		             ->setParameter('username', $username);

		return $query->getOneOrNullResult();
	}

	public function getUserWithCompany($username, \AppBundle\Empresa $company)
	{
		$query = $this->getEntityManager()
		            ->createQuery(
		                			'SELECT u 
		                			 FROM AppBundle:Usuario u 
		                			 WHERE u.activo = :activo AND u.username = :username AND u.empresa = :empresa'
		            )->setParameter('empresa', $company)
		             ->setParameter('activo', true)
		             ->setParameter('username', $username);

		return $query->getOneOrNullResult();
	}
}
