<?php

namespace GestionBundle\Repository\segVial\eventos;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends \Doctrine\ORM\EntityRepository
{

    public function proximoNumeroEvento($class)
    {
        $query = $this->createQueryBuilder('e')
                     ->select('MAX(e.numero) AS max_numero')
                     ->where('e INSTANCE OF :instance')->setParameter('instance', $class);
        return ($query->getQuery()->getSingleScalarResult() + 1);
    }
}
