<?php

namespace GestionBundle\Repository\segVial\eventos;

/**
 * TipoSucesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSucesoRepository extends \Doctrine\ORM\EntityRepository
{
}
