<?php

namespace GestionBundle\Repository\segVial\eventos;

/**
 * TipoInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInfraccionRepository extends \Doctrine\ORM\EntityRepository
{
}
