<?php

namespace GestionBundle\Repository\segVial\eventos;

/**
 * UbicacionEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
