<?php

namespace GestionBundle\Repository\segVial\opciones;

/**
 * TipoUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabilitacionUnidadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTiposHabilitacionActiva()
    {
        $data =  $this->createQueryBuilder('u')
                        ->where('u.activa = :activo')
                        ->setParameter('activo', true)
                        ->getQuery()
                        ->getResult();
        return $data;
    }
}
