<?php

namespace GestionBundle\Repository\segVial\opciones;

/**
 * TipoHabilitacionUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHabilitacionUnidadRepository extends \Doctrine\ORM\EntityRepository
{
}
