<?php

namespace GestionBundle\Repository\segVial\opciones;

/**
 * TipoSuspensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSuspensionRepository extends \Doctrine\ORM\EntityRepository
{
}
