<?php

namespace GestionBundle\Repository\trafico;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getServiciosCliente(\GestionBundle\Entity\ventas\Cliente $cliente, \AppBundle\Entity\Estructura $estructura = null)
	{
		$data =  $this->createQueryBuilder('s')
					    ->where('s.cliente = :cliente')
					    ->andWhere('s.estructura = :estructura')
					    ->setParameter('cliente', $cliente)
					    ->setParameter('estructura', $estructura)
					    ->orderBy('s.nombre', 'ASC')
					    ->getQuery()
					    ->getResult();
		return $data;
	}
}
