<?php

namespace GestionBundle\Repository\segVial\peajes;

/**
 * EstacionPeajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstacionPeajeRepository extends \Doctrine\ORM\EntityRepository
{
}
