<?php

namespace GestionBundle\Repository\segVial\peajes;

/**
 * TarifaPeajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaPeajeRepository extends \Doctrine\ORM\EntityRepository
{
}
