<?php

namespace GestionBundle\Repository\rrhh\opciones;

/**
 * TipoVencimientoEstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoVencimientoEstructuraRepository extends \Doctrine\ORM\EntityRepository
{
}
