<?php

namespace GestionBundle\Repository\ventas;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllCiudades(\AppBundle\Entity\Estructura $estructura = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select(array('c.id as id, c.nombre as ciudad, p.nombre as provincia, c.latitud, c.longitud, p.id as idpcia'))
            ->join('c.provincia', 'p');
        if ($estructura)
        {
            $qb->where($qb->expr()->isMemberOf(':str', 'c.estructuras'))
               ->setParameter('str', $estructura);
        }

       return $qb->orderBy('c.nombre', 'ASC')
                 ->getQuery()
                 ->getResult();
    }
}
