<?php

namespace GestionBundle\Repository\ventas;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAllClientes()
	{
		return $this->createQueryBuilder('c')
					 ->select('c.id, c.prefijo, c.razonSocial, c.nombreFantasia, c.domicilioFiscal, 
					 		  c.tipoFactura, c.condicionPago, c.tipoAjuste, c.frecuencaAjuste,
					 		  c.nombreContacto, c.telefonoContacto, c.mailContacto, c.celularContacto, c.activo')
				     ->orderBy('c.razonSocial', 'ASC')
				     ->getQuery()
				     ->getResult();
	}
}
