<?php

namespace GestionBundle\Repository\ventas;

/**
 * UbicacionEstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionEstructuraClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
