<?php

namespace GestionBundle\Repository\trafico\opciones;

/**
 * TipoServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
